#!/usr/bin/env python3
import json
import sys
from pathlib import Path
from typing import Any, Dict

def convert_rich_to_minimal(rich: Dict[str, Any]) -> Dict[str, Any]:
    """
    Take a USJ-Rich v1.0 document and produce a USJ-Minimal v1.0 document.

    - Keeps: usj_version (changed), id, language, scope, metadata, books
    - Flattens books:
        books[book_code][f"{chapter}:{verse}"] = verse_text
    - Drops: name, titles, chapters/verses structure, block, strongs,
             footnotes, words, headings, etc.
    """
    minimal: Dict[str, Any] = {
        "usj_version": "1.0-minimal",
        "id": rich.get("id"),
        "language": rich.get("language"),
        "scope": rich.get("scope"),
        "metadata": rich.get("metadata", {}),
        "books": {},
    }

    books = rich.get("books", {})
    for book_code, book_obj in books.items():
        chapters = book_obj.get("chapters", {})
        flat_book: Dict[str, str] = {}

        for chapter_key, chapter_obj in chapters.items():
            verses = chapter_obj.get("verses", {})
            for verse_key, verse_obj in verses.items():
                verse_text = verse_obj.get("text", "")
                # Key format: "chapter:verse"
                cv_key = f"{chapter_key}:{verse_key}"
                flat_book[cv_key] = verse_text

        # Always include the book code, even if no verses (e.g. FRT, FRT with no chapters)
        minimal["books"][book_code] = flat_book

    return minimal


def process_file(path: Path) -> None:
    """
    Load a rich JSON file, convert to minimal, write *_minimal.json next to it.
    """
    print(f"Processing {path} ...")
    with path.open("r", encoding="utf-8") as infile:
        rich = json.load(infile)

    minimal = convert_rich_to_minimal(rich)

    output_path = path.with_name(path.stem + "_minimal.json")
    with output_path.open("w", encoding="utf-8") as outfile:
        json.dump(minimal, outfile, ensure_ascii=False, indent=2)

    print(f"  -> Wrote {output_path}")


def main(argv: list[str]) -> None:
    args = argv[1:]

    if args:
        input_files = [Path(a) for a in args]
    else:
        # Default to the rich JSON files generated by usfx2json.py
        input_files = [Path("bible_kjv.json"), Path("bible_web.json")]

    for path in input_files:
        if not path.exists():
            print(f"Skipping {path} (file not found)")
            continue
        process_file(path)


if __name__ == "__main__":
    main(sys.argv)

